### ISSUE TITLE
Extend indexing on PDB.p2:

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/vfb-pipeline-update-prod#2]
Minimal:

:Entity short_form
:DataSet short_form
:Site short_form
:pub short_form
:Template short_form
:License short_form

(in addition to existing indexes)

**Comment by dosumis** [comment]
This should, of course, be configurable.  Indexing needs will change as the project evolves.

**Comment by matentzn** [comment]
This is untested as of yet, but if it works, it can be configured [here](https://github.com/VirtualFlyBrain/vfb-pipeline-update-prod/blob/master/pdb_set_indices.neo4j)

**Comment by matentzn** [comment]
Works now: http://pdbl.p2.virtualflybrain.org/browser/ (`:schema`). It was so obvious to test that I will close this ticket for you.
